var errorMessages = {
  SESSION_KEY_REQUIRED: 'sessionKey header missing.',
  INVALID_SESSION_KEY: 'Invalid session key.',
  EMAIL_ALREADY_REGISTERED: 'This email has already been registered.',
  INVALID_AUTH_TOKEN: 'Invalid authToken.',
  INVALID_RANDOM_SALT: 'Invalid randomSalt.',
  INVALID_EMAIL: 'Invalid email number.',
  INVALID_EMAIL_OR_PASSWORD: 'Invalid email or password.',
  USER_NOT_FOUND: 'The user couldn\'t be found.',
  INVALID_USER_DATA: 'Invalid userData.',
  INVALID_PASSWORD: 'Invalid password.',
  INVALID_PUBLIC_KEY: 'Invalid public key.',
  INVALID_WALLET_KEY: 'Invalid wallet key.',
  INVALID_WALLET_ID: 'Invalid walletID.',
  INVALID_SIGNATURE: 'Invalid signature.',
  SIGNATURE_ALREADY_WRITTEN: 'The wallet\'s signature has already been written.',
  INVALID_ADDRESS_STRING_AND_CHILD_NUM: 'Invalid addressString and childNum combination for this wallet.',
  INVALID_DESTINATION_ADDRESS: 'Invalid destinationAddressString.',
  INVALID_INPUT_ADDRESS: 'Invalid input address.',
  INPUT_ADDRESS_MISMATCH: 'The input address doesn\'t match the expected wallet address at the given index.',
  INVALID_PARAM: 'Invalid parameter.',
  USER_WALLET_ALREADY_EXISTS: 'The user\'s wallet has already been created.', 
  ADDRESS_NOT_SEQUENTIAL: 'The address childNum is too high.',
  ADDRESS_ALREADY_CREATED: 'The address was already created.',
};

exports.errorMessages = errorMessages;
